add test for netperf and provide install hint on failure

diff --git a/BettererSpeedTest b/BettererSpeedTest
--- a/BettererSpeedTest
+++ b/BettererSpeedTest
@@ -56,6 +56,13 @@ usage() {
         exit 1
 }
 
+prereqs() {
+	echo "Can't find the netperf binary in your current path"
+	echo "use your package manager to install netperf"
+	echo ""
+	exit 1
+}
+
 # Summarize the contents of the ping's output file to show min, avg, median, max, etc.
 # 	input parameter ($1) file contains the output of the ping command
 
@@ -212,6 +219,8 @@ measure_direction() {
 [[ -r /etc/bettererc ]] && . /etc/bettererc
 [[ -r /etc/default/bettererc ]] && . /etc/default/bettererc
 [[ -r ${HOME}/.bettererc ]] && . ${HOME}/.bettererc
+
+[[ -z $(which netperf) ]] && prereqs
 
 # extract options and their arguments into variables.
 while [ $# -gt 0 ] 
